apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: chat-network-rules
spec:
  rules:
  - host: chatty-ingress.tk
    http:
      paths:
      - path: /
        backend:
          serviceName: chat-web-service
          servicePort: 80
      - path: /redis
        backend:
          serviceName: chat-redis-service
          servicePort: 80
      - path: /socket
        backend:
          serviceName: chat-socket-service
          servicePort: 80
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: chat-nginx-ingress-controller
  labels:
    chatapp: nginx-ingress-lb
spec:
  replicas: 1
  selector:
    chatapp: nginx-ingress-lb
  template:
    metadata:
      name: nginx-ingress-lb
      labels:
        chatapp: nginx-ingress-lb
    spec:
      terminationGracePeriodSeconds: 60
      containers:
        - name: nginx-ingress-lb
          image: quay.io/kubernetes-ingress-controller/nginx-ingress-controller:0.24.1
          imagePullPolicy: Always
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /healthz
              port: 10254
              scheme: HTTP
            periodSeconds: 10
            successThreshold: 1
            timeoutSeconds: 1
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: POD_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          ports:
            - containerPort: 80
              hostPort: 80
            - containerPort: 443
              hostPort: 443
          args:
            - /nginx-ingress-controller