apiVersion: v1
kind: Service
metadata:
  name: chat-redis-service
spec:
  selector:
    app: chat-redis-pod
  ports:
  - port: 80
    nodePort: 32121
    targetPort: 3333
    protocol: TCP
    name: http
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-redis-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: chat-redis-pod
  template:
    metadata:
      labels:
        app: chat-redis-pod
    spec:
      containers:
      - name: chat-redis-container
        image: redis
        resources:
          limits:
            memory: "128Mi"
            cpu: "300m"
        ports:
        - name: chat-r-port
          containerPort: 3333
