apiVersion: v1
kind: Service
metadata:
  name: chat-socket-service
spec:
  selector:
    app: chat-socket-pod
  ports:
  - port: 80
    nodePort: 31000
    targetPort: 2222
    protocol: TCP
    name: http
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-socket-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: chat-socket-pod
  template:
    metadata:
      labels:
        app: chat-socket-pod
    spec:
      containers:
      - name: chat-socket-container
        image: tylerilunga/chatapp:socket1.1
        env:
        - name: REDISHOST
          value: "chatty-ingress.tk/redis" # review
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - name: chat-s-port
          containerPort: 2222
